backend:
  name: github
  branch: main # change this to your branch
  repo: SzymonMirek/FantasticaEnsemble # change this to your repo
  site_domain: www.fantasticaensemble.com # change this to your domain
  base_url: https://www.fantasticaensemble.com # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

media_folder: "static/uploads"  # or your preferred media folder path
media_library:
  name: uploadcare  # or another supported media library

collections:

  - name: "wydarzenia"
    label: "Wydarzenia"
    folder: "src/content/wydarzenia"  # Astro Content Collections path
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    create: true  # ← THIS MUST BE ENABLED
    fields:
      # Date Block (matches your HTML structure)
      - label: "Data wydarzenia"
        name: "dataWydarzenia"  # CamelCase for cleaner frontmatter
        widget: object
        fields:
          - {label: "Dzień", name: "dzien", widget: string}
          - {label: "Miesiąc i Rok", name: "mR", widget: string}  # "paź<br>2025"

      # Other fields (preserve your class names)
      - {label: "Repertuar", name: "repertuar", widget: string}
      - {label: "Nazwa wydarzenia", name: "nazwaWydarzenia", widget: string}
      - {label: "Miejsce", name: "miejsceWydarzenia", widget: string}
      - {label: "Godzina", name: "czasWydarzenia", widget: string}
      - {label: "Link do wydarzenia", name: "linkWydarzenia", widget: string, required: false }

  - name: "events"
    label: "Wydarzenia (EN)"
    folder: "src/content/events"  # Astro Content Collections path
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    create: true  # ← THIS MUST BE ENABLED
    fields:
      # Date Block (matches your HTML structure)
      - label: "Event date"
        name: "eventDate"  # CamelCase for cleaner frontmatter
        widget: object
        fields:
          - {label: "Day", name: "day", widget: string}
          - {label: "Month and Year", name: "monthYear", widget: string}  # e.g., "Oct<br>2025"

      # Other fields (preserve your class names)
      - {label: "Repertoire", name: "repertoire", widget: string}
      - {label: "Event name", name: "eventName", widget: string}
      - {label: "Location", name: "eventLocation", widget: string}
      - {label: "Time", name: "eventTime", widget: string}
      - {label: "Event link", name: "eventLink", widget: string, required: false }