backend:
  name: github  # or gitlab, bitbucket
  repo: SzymonMirek/FantasticaEnsemble  # e.g., my-org/my-site
  branch: main

media_folder: "static/uploads"  # or your preferred media folder path
media_library:
  name: uploadcare  # or another supported media library

collections:
  # Your collections go here
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }