backend:
  name: github  # or gitlab, bitbucket
  repo: SzymonMirek/FantasticaEnsemble  # e.g., my-org/my-site
  branch: main
  base_url: https://www.fantasticaensemble.com # This is critical for production


media_folder: "static/uploads"  # or your preferred media folder path
media_library:
  name: uploadcare  # or another supported media library

collections:
  - name: "wydarzenia"
    label: "Wydarzenia"
    folder: "src/content/wydarzenia"  # Astro Content Collections path
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    create: true  # ← THIS MUST BE ENABLED
    fields:
      # Date Block (matches your HTML structure)
      - label: "Data wydarzenia"
        name: "dataWydarzenia"  # CamelCase for cleaner frontmatter
        widget: object
        fields:
          - {label: "Dzień", name: "dzien", widget: string}
          - {label: "Miesiąc i Rok", name: "mR", widget: string}  # "paź<br>2025"

      # Other fields (preserve your class names)
      - {label: "Nazwa wydarzenia", name: "nazwaWydarzenia", widget: string}
      - {label: "Opis wydarzenia", name: "opisWydarzenia", widget: string}
      - {label: "Miejsce", name: "miejsceWydarzenia", widget: string}
      - {label: "Godzina", name: "czasWydarzenia", widget: string}
      - {label: "Link do wydarzenia", name: "linkWydarzenia", widget: string, required: false }